#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - wget
  - gnupg-agent
  - software-properties-common
  - git
  - haproxy
runcmd:
  - cd /opt
  - git clone https://github.com/hiddify/hiddify-config/
  - cd hiddify-config
  # uncomment it for using a special secret other wise it will be createed automatically/
  #- echo "USER_SECRET=44da16ea20ff4bac92afae43ef97f067" >config.env
  #- echo "MAIN_DOMAIN=terra.aminsaedi.bio" >>config.env
  - bash install.sh


# please open http://yourip/ or https://yourip.sslip.io within the one hour after setuping your server