---

- name: Add haproxy repository
  apt_repository:
    repo: ppa:vbernat/haproxy-2.8
    state: present

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ REQUIRED_PACKAGES }}"


- name: Download hiddify
  get_url:
    url: "https://github.com/hiddify/hiddify-config/releases/latest/download/hiddify-config.zip"
    dest: /opt

- name: Create hiddify-config directory
  file:
    path: /opt/hiddify-config
    state: directory

- name: Unzip hiddify
  unarchive:
    src: /opt/hiddify-config.zip
    dest: /opt/hiddify-config
    remote_src: yes

- name: Run the hiddify install script
  shell: /opt/hiddify-config/install.sh > /tmp/install_log


- name: Copy set-fqdn script to remote machine
  copy:
    src: tmp/set-fqdn.py
    dest: /tmp/set-fqdn.py
    owner: root
  tags:
    - panel


- name: Install python selenium package
  pip:
    name: selenium
  tags:
    - panel


- name: Run the script to set the panel fqdn
  shell: "python3 /tmp/set-fqdn.py {{ fqdn }}"
  tags:
    - panel
